# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install system dependencies
        run: |
          # sudo apt-get update
          # sudo apt-get install -y python3-setuptools python3-pip
          # pip3 install numpy
          # pip3 install wheel
          # pip3 install cython
          # pip3 install macs3
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "BiocManager"))
          BiocManager::install("S4Vectors")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
